### ISSUE TITLE
Error creating dictation_session_create

### ISSUE THREAD

**Issue by Sprechen** [pebble-examples/simple-voice-demo#1]
I have imported your project into the Cloud Pebble IDE. On my pebble time (firmware version 3.6) the dictation_session_create return null.

I use Italian language, and other system app the dictation works fine.

Maybe the firmware version 3.6 still doesn't support the dictation api?

Thank you very much!

**Comment by yeahdef** [comment]
I also cannot get this to work as expected on Pebble Time.
I have tried this:
clone this repo.
pebble clean
pebble build
pebble install build/simple-voice-demo.pbw

I get the app on my pebble watch, but it sits on the screen "Press Select to get input".
No buttons begin the dictation?

**Comment by yeahdef** [comment]
My problem was that I didn't have the latest pebble time app version installed on my phone.

**Comment by C-D-Lewis** [comment]
Yes, you should ensure your phone app is also up to date.
